### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by pdhruska** [anitschke/go-nixplay#1]
Forgive me if this isn't the best way to contact you, but I only dabble with git and I couldn't find another way.

Although I don't have much experience with go, I do share the objective I believe you are trying to create with go-nixplay and it's integration with rclone.  If there is anything I can to to help move this effort forward, I'd be happy to assist.  Please let me know.

Cheers

**Comment by anitschke** [comment]
Thanks for reaching out. At this point things are going well and the go based API am I am writing here in go-nixplay is in a working state with just a few minor bugs to squash and some other cleanup items (I know it may not look like it but that is just because I haven't pushed any code out to the main branch yet).

I have also already done some prototype integration with rclone that seems to mostly work. So at this point I think I should just need to integrate the two and add testing on the rclone side of things.

All that said there are a few things that I could probably use a hand with:
1. I'll need to add some documentation for the nixplay backend to rclone. They have some discussion of that towards the end of the [writing a new backend](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend) section of their doc.
2. Once I get something working it would be good to have another person beta test it / bash on it to see if there are any issues that I may not have found during testing.

Does any of that sound like something you might be interested in? Or were you more looking to get your hands dirty in some of the code?

**Comment by pdhruska** [comment]
My apologies.. work got a bit overwhelming.

Assisting with documentation and beta testing are activities where I would be able to potentially add value.  I don't have a very deep background with go and would likely be more of a hinderance to you there.

I'll dig into the documentation requirements you linked to above and see what will be necessary for the new capability.

As for banging at the functionality and exercising some use cases against it, let me know when the code is ready to be whacked at.

If you would like to collaborate via e-mail, you can contact me using my username at the big "G".

Cheers
